StartupEvents.registry("item", (e) => {
  e.create(`anel_1`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel1`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_2`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel2`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_3`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel3`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_4`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel4`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_5`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel5`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_6`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel6`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_7`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel7`)
    .rarity("epic")
    .unstackable();
  e.create(`anel_8`)
    .displayName("Aliança")
    .texture(`kubejs:item/rings/anel8`)
    .rarity("epic")
    .unstackable();
});
