StartupEvents.registry('block', e => {
    //! BLACKJACK
    e.create("blackjack") 
    .displayName("Blackjack")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/blackjack')
    //! CLASSIC
    e.create("classic") 
    .displayName("Classic")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/classic')
    //! CRASH
    e.create("crash") 
    .displayName("Crash")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/crash')
    //! DARTS
    e.create("darts") 
    .displayName("Darts")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/darts')
    //! DEADMANSCHEST
    e.create("deadmanschest") 
    .displayName("Deadmanschest")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/deadmanschest')
    //! DICE
    e.create("dice") 
    .displayName("Dice")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/dice')
    //! DRUMS
    e.create("drums") 
    .displayName("Drums")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/drums')
    //! LOTTERY
    e.create("lottery") 
    .displayName("Lottery")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/lottery')
    //! POKER
    e.create("poker") 
    .displayName("Poker")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/poker')
    //! PYRAIMD
    e.create("pyramid") 
    .displayName("Pyramid")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/pyramid')
    //! RACES
    e.create("races") 
    .displayName("Races")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/races')
    //! ROCK PAPERS CISSORS
    e.create("rockpaperscissors") 
    .displayName("Rock Paper Cissors")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('rockpaperscissors')
    .model('kubejs:block/drums')
    //! ROULETTE
    e.create("roulette") 
    .displayName("Roulette")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/roulette')
    //! STAIRS
    e.create("stairs") 
    .displayName("Stairs")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/stairs')
    //! TICTACTOE
    e.create("tictactor") 
    .displayName("Tictactoe")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .unbreakable()
    .renderType('translucent')
    .model('kubejs:block/tictactoe')
})