StartupEvents.registry('block', e => {
    //! BLACKJACK
    e.create("rdf_blackjack") 
    .displayName("Blackjack")
    .material("wood")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/blackjack')
    //! CLASSIC
    e.create("rdf_classic") 
    .displayName("Classic")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/classic')
    //! CRASH
    e.create("rdf_crash") 
    .displayName("Crash")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/crash')
    //! DARTS
    e.create("rdf_darts") 
    .displayName("Darts")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/darts')
    //! DEADMANSCHEST
    e.create("rdf_deadmanschest") 
    .displayName("Deadmanschest")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/deadmanschest')
    //! DICE
    e.create("rdf_dice") 
    .displayName("Dice")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/dice')
    //! DRUMS
    e.create("rdf_drums") 
    .displayName("Drums")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/drums')
    //! LOTTERY
    e.create("rdf_lottery") 
    .displayName("Lottery")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/lottery')
    //! POKER
    e.create("rdf_poker") 
    .displayName("Poker")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/poker')
    //! PYRAIMD
    e.create("rdf_pyramid") 
    .displayName("Pyramid")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/pyramid')
    //! RACES
    e.create("rdf_races") 
    .displayName("Races")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/races')
    //! ROCK PAPERS CISSORS
    e.create("rdf_rockpaperscissors") 
    .displayName("Rock Paper Cissors")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .renderType('rockpaperscissors')
    .model('kubejs:block/drums')
    //! ROULETTE
    e.create("rdf_roulette") 
    .displayName("Roulette")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/roulette')
    //! STAIRS
    e.create("rdf_stairs") 
    .displayName("Stairs")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/stairs')
    //! TICTACTOE
    e.create("rdf_tictactor") 
    .displayName("Tictactoe")
    .material("metal")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .model('kubejs:block/tictactoe')
})