StartupEvents.registry('block', e => {
    //! plushie 1 (mago)
    e.create("mago_plushie") 
    .displayName("Mago Plushie")
    .material("wool")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .notSolid()
    .noCollision()
    .model('kubejs:block/omago')
    
    .model('kubejs:block/maguinho')
    //! plushie 2 (roda)
    e.create("roda_plushie") 
    .displayName("Roda da Fortuna Plushie")
    .material("wool")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .notSolid()
    .noCollision()
    .model('kubejs:block/rodinha')

    //! plushie 3 (axolot)
    e.create("kubejs_plushie") 
    .displayName("Axolot Plushie")
    .material("wool")
    .hardness(1.0)
    .resistance(1.0)
    .noValidSpawns(true)
    .notSolid()
    .noCollision()
    .model('kubejs:block/babyaxolotl')
})